name: image_editor_plus
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 0.2.1
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/image_editor_plus

environment:
    sdk: ">=2.15.1 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  screenshot: ^2.1.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.0.2
  image: ^4.0.15
  image_editor: ^1.0.2
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.0
  flutter_image_compress: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
    uses-material-design: true
