name: image_editor_plus
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 0.0.9
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/image_editor_plus

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  zoom_widget: ^0.2.1
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.1
  permission_handler: ^8.3.0
  screenshot: ^1.2.3
  flutter_colorpicker: ^1.0.3
  collection: ^1.15.0
  nb_utils: ^4.4.11
  extended_image: ^6.0.1
  crop: ^0.5.2
  image: ^3.1.1
  image_editor: ^1.0.2
  colorfilter_generator: ^0.0.6
  hand_signature: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: