name: image_editor_plus
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 1.0.6
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/image_editor_plus

environment:
    sdk: ">=2.17.3 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.0
  screenshot: ^3.0.0
  extended_image: ^8.1.0
  image: ^4.0.15
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.0
  reorderables: ^0.6.0
  permission_handler: ^11.1.0
  flex_color_picker: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
