name: image_editor_plus
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 1.0.3
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/image_editor_plus

environment:
    sdk: ">=2.17.3 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.0
  screenshot: ^2.1.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.1.0
  image: ^4.0.15
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.0
  flutter_image_compress: ^2.0.3
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
    uses-material-design: true
